name: Test Pull Request

on:

  pull_request:

    branches: [ master ]

  steps:

      - name: Checkout Repository
      uses: actions/checkout@v2
      - name: Install Environment
      uses: 

runs:
  using: 'docker'
  image: 'Dockerfile'